name: Run Jest Tests

on:
  push:           # Corre cuando haces push
    branches: ["main"]
  pull_request:   # Corre cuando abres PR hacia main
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.18.0
      - run: npm ci
      - run: npm test


