jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.18.0
      - run: npm ci
      - run: npx eslint . --ext .js,.jsx,.ts,.tsx

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.18.0
      - run: npm ci
      - run: npm test